ARCHS = armv7 armv7s arm64
SDKVERSION = 7.0

include @@THEOS@@/makefiles/common.mk

BUNDLE_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = Toggle.xm
@@PROJECTNAME@@_INSTALL_PATH = /Library/Application Support/CCToggles/QuickLaunches

include $(THEOS_MAKE_PATH)/bundle.mk

